service: serverless-event-driven

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  environment:
    DYNAMODB_TABLE: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:us-west-2:*:table/${self:custom.tableName}

functions:
  apiHandler:
    handler: handlers/api_handler.handler
    events:
      - http:
          path: api/{id}
          method: get

  processHandler:
    handler: handlers/process_handler.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.events"
            detail-type:
              - "Scheduled Event"

  notifyHandler:
    handler: handlers/notify_handler.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.cloudwatch"
            detail-type:
              - "CloudWatch Alarm State Change"

resources:
  Resources:
    MyDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

custom:
  tableName: the_table
